### ISSUE TITLE
Update vsphere docs on kubernetes.io 

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/vsphere-storage-for-kubernetes#3]
Update [Kubernetes.io getting started guide](https://kubernetes.io/docs/getting-started-guides/vsphere/) with quick summary and redirect to [vSphere Storage for Kubernetes](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/) for details.

CC/ @divyenpatel @BaluDontu

**Comment by divyenpatel** [comment]
PR: https://github.com/kubernetes/kubernetes.github.io/pull/5241

**Comment by divyenpatel** [comment]
PR merged. closing this issue.
