### ISSUE TITLE
FAQ contains a broken link for HA section 

### ISSUE THREAD

**Issue by prashima** [vmware/vsphere-storage-for-kubernetes#30]
Link to the high availability section mentioned in https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/faqs.html#how-kubernetes-volumes-can-be-made-resilient-to-failures-on-vsan-datastore is broken.

**Comment by divyenpatel** [comment]
Need to correct the link - https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/high-availability.html
