### ISSUE TITLE
Pemissions needed

### ISSUE THREAD

**Issue by freeseacher** [vmware/vsphere-storage-for-kubernetes#37]
Hi! 
I am trying to use that provider as an vsphere user. My it team does not gave me admin permissions on the vmware cluster and i am wondering what minimal permissions do i need to use it?

Currently we are using vmware vsphere 6.7. the same behaviour was on 6.5. 
We are trying to debug with govc and it looks like this 
```
[shirokih-laptop] 13:13:41 ~/k8s/pv % govc datastore.disk.create -d=thin -ds Datastore2 -size 20G k8s/node5.vmdk
[08-08-18 14:24:07] Creating [Datastore2] k8s/node5.vmdk...^C
```
as you can see operation was not finished for an about an hour

file was created but it looks like operation for its creation was not finished somehow. 
there https://www.bountysource.com/issues/57265124-persistencevolumeclaim-stuck-in-pending-state-dispite-disk-having-been-created-in-vcenter

that sort of issue was mentioned too. but with no details how to fix it.

**Comment by divyenpatel** [comment]
@freeseacher you need  `Datastore.FileManagement (Low level file operations)` Privileges on the `Datastore2` for your user. also make sure you have read privileges to track disk creation progress.

Please refer - 
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html#minimal-set-of-vsphere-rolesprivileges-required-for-static-only-persistent-volume-provisioning

**Comment by freeseacher** [comment]
In case any one will find that issue. 
Probably the permission you missing is 
```
<fault xsi:type="NoPermission"><object type="Folder">group-d1</object><privilegeId>System.Read</privilegeId></fault>
```
it can be found in debug folder
