### ISSUE TITLE
slack invite needed

### ISSUE THREAD

**Issue by davidkarlsen** [vmware/vsphere-storage-for-kubernetes#38]
https://github.com/vmware/vsphere-storage-for-kubernetes
states that you can join slack,
but when I want to join it states "If you have an @vmware.com or @emc.com email address, you can create an account."

Do you have a sign-up mechanism for people outside of vmware or emc?

If not - the text could be adapted to inform that it is a closed-community only.

**Comment by divyenpatel** [comment]
Will update to reach out at https://kubernetes.slack.com/messages/sig-vmware

**Comment by divyenpatel** [comment]
Updated in https://github.com/vmware/vsphere-storage-for-kubernetes/pull/39
