### ISSUE TITLE
snapshotting in vSphere Storage (question)

### ISSUE THREAD

**Issue by nustiueudinastea** [vmware/vsphere-storage-for-kubernetes#52]
Hi everyone,

Thanks for this awesome project!

I was wondering, does vmware plan on providing snapshotting capabilities through the fairly new volume snapshotting API present in K8s?

**Comment by mylesagray** [comment]
@nustiueudinastea that is more of a question for the CSI implementation we are working on here as CSI contains the snapshotting spec: https://github.com/kubernetes-sigs/vsphere-csi-driver

**Comment by nustiueudinastea** [comment]
Ah, of course, that makes sense! Thanks
