### ISSUE TITLE
 Add support vSphere Datastore Cluster

### ISSUE THREAD

**Issue by creativie** [vmware/vsphere-storage-for-kubernetes#60]
Now vSphere Cloud Provider supports only datastore object as storage source.
It would be nice if the driver supported working with the datastore cluster

**Comment by divyenpatel** [comment]
@creativie by Driver mean - vSphere CSI Driver - https://github.com/kubernetes-sigs/vsphere-csi-driver

If you are looking for this feature in the in-tree plugin,  In-tree vSphere plug-in is already deprecated and we are working on enabling migration of workload to vSphere CSI driver.

Please refer following.

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/README.md
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/plugins.go#L47

**Comment by Sam-Lin-MillersLab** [comment]
So "vsphere-storage-for-kubernetes" is deprecated?
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/index.html

I wonder why there is no such notice on the doc.
